# Generated by Django 5.0.6 on 2024-07-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_name', models.CharField(max_length=50)),
                ('events_date', models.DateField()),
                ('events_time', models.TimeField()),
                ('events_description', models.TextField()),
            ],
        ),
    ]
